### ISSUE TITLE
GitLab v15.2/v15.3 - 500 Error on (first) login

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1315]
Unfortunately, it appears that the recently released GitLab v15.2 appliance (which provides GitLab via Omnibus installer) has a pretty serious [bug](https://www.turnkeylinux.org/comment/33694#comment-33694) where initial login gives a 500 error... :cry:

I intend to re-release ASAP. In the meantime, to workaround the issue, log in via SSH and run the following commands:
```
mv /etc/gitlab/gitlab-secrets.json /etc/gitlab/gitlab-secrets.json.bak
gitlab-rails runner -e production "ApplicationSetting.current.reset_runners_registration_token!"
/usr/lib/inithooks/bin/gitlab.py
```
And (re)set your password, email and domain.

Everything should now work...

**Comment by OnGle** [comment]
This issue did not get properly fixed, and will remain open until it is.

**Comment by JedMeister** [comment]
This issue has been resolved in the buildcode and v15.4 should be released really soon (this week hopefully)...

**Comment by jasper-bosch** [comment]
I just downloaded [v15.4](https://www.turnkeylinux.org/download?file=turnkey-gitlab-15.4-stretch-amd64.ova) and got the 500 error on login. Did I download an old build or is the issue still there?

**Comment by JedMeister** [comment]
@jasper-bosch - Thanks for reporting.

It _should_ be fixed in v15.4 as I tested the ISO myself prior to release and it worked fine for me! Although having said that, it should have also been fixed in v15.3 too (and wasn't...) so I'll download the OVA now and test it myself.

Essentially the OVA should give the same result as installing from the ISO in the same environment. However, the OVA comes with pre-configured resource allocation. GItLab is a beast at the best of times and is pretty resource hungry. Perhaps the default resources allocated in the OVA are insufficient for more recent versions of GitLab?

I'll post back with my results ASAP, but it might be worth bumping up the RAM allocated to your VM and see if that helps?

**Comment by JedMeister** [comment]
Argh! You are right... I can reproduce this with the v15.4 GitLab appliance launched from a freshly downloaded OVA... :sob: 

However, I'm pretty sure that the actual cause is slightly different to the previous issue. My research so far suggests that it's caused by a race condition when the resources are too low (GitLab being such a beast it's a bit slow to start). I'm assuming that's why it worked for me when I tested the ISO (KVM VM with 4GB RAM & 2 vCPUs on my server), but not when launched from the OVA (defaults to 1GB RAM & 1 vCPU within VirtualBox on my laptop). I I tried launching it from the OVA with RAM bumped up to 3GB prior to first boot the issue still occurs. When I watched it closely, it appears that some output flashes on the terminal at the end of the GitLab inithook. I'm not 100% sure, but I strongly suspect that is the issue...

I haven't yet had a chance to double check with 4GB RAM (what I used for my pre-release tests), but if I rerun the `gitlab-rails` command with GitLab running (i.e. after the 500 error - command as noted in the OP and again below) that appears to resolve it.

```
gitlab-rails runner -e production "ApplicationSetting.current.reset_runners_registration_token!"
```

**Comment by jasper-bosch** [comment]
@JedMeister It was running in a VM on my PC. The VM had 4 GB of RAM and 1 vCPU.

> I'm assuming that's why it worked for me when I tested the ISO (KVM VM with 4GB RAM & 2 vCPUs on my server)

After reading your comment I tried running it in a new VM with 5 GB of RAM and 2 vCPUs, but I still got the 500 error on login.

Running the command you mentioned did indeed resolve it. Thanks!

**Comment by JedMeister** [comment]
Hey @jasper-bosch I'm really glad to hear that the workaround worked for you. At least that's something...

When you say that your VM had "4 GB of RAM and 1 vCPU", then "5 GB of RAM and 2 vCPUs", but you still got the error, was that bumping the resource _**before**_ firstboot (of a fresh install)? Or did you bump the resources of an existing VM?

If it was the former (i.e. bumped resources **_prior_** to first boot), I would have expected that to "just work" and if not, then there's still something I'm missing somewhere...

If it was the latter (i.e. booted with default resources, then bumped them up **_after_** first boot), then that's (somewhat) expected (assuming that my understanding of the race condition issue is correct). Obviously it's still not right and needs a fix, but it would conform with my understanding of what is going on.

FWIW that command (that fixed the issue) runs at firstboot (or at least should run at firstboot). We added that in the v15.3 build (but it was still broken). For v15.4 we moved it to later in the boot process (see https://github.com/turnkeylinux-apps/gitlab/commit/0e9f833ab6305c005fc44f4f603134d70d074a8a) but obviously that wasn't enough...

I'm going to leave this issue closed, but have just opened a new one against 15.4.

**Comment by jasper-bosch** [comment]
> When you say that your VM had "4 GB of RAM and 1 vCPU", then "5 GB of RAM and 2 vCPUs", but you still got the error, was that bumping the resource before firstboot (of a fresh install)? Or did you bump the resources of an existing VM?

That was bumping the resources before first boot of a fresh install.

**Comment by JedMeister** [comment]
> That was bumping the resources before first boot of a fresh install.

Hmm ok, thanks for the clarification...

I'll hopefully get back to this early next week and have another try...

**Comment by clayshek** [comment]
I can report that I experience the same issue (500 error on first login) with the 15.4 ISO downloaded today, and that the workaround documented in the original post resolves it.

**Comment by JedMeister** [comment]
Thanks @clayshek - Apologies that I've been a little slow on the turnaround with this.

I've been working on it and (finally) have (what I believe to be) a rock solid resolution. Yesterday I tested the new prototype in a VirtualBox VM with 2GB RAM and 1 vCPU. It was slow and painful to use with so little resources, but it worked!

I hope to rebuild using our infrastructure within the next few days, and I'll then do some final testing (really it's a bit embarrassing that we've had to take so many stabs at this one...). Hopefully we should have it (v15.5) public by weeks end; early next week at the latest.
