### ISSUE TITLE
Mayan-EDMS logging config

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1523]
We should tidying up the logging config for the Mayan-EDMS appliance.

As noted by [Sensiva in the forums](https://www.turnkeylinux.org/comment/48943#comment-48943) `/var/log/mayan` is empty and the Mayan `config.yml` use a location of `/opt/mayan-edms/media/error.log`.

As noted in my response, we should either make the `/var/log` location a symlink to where the logs really are, or reconfigure Mayan to log to `/var/log/mayan`. The [logrotate config](https://github.com/turnkeylinux-apps/mayan-edms/blob/master/overlay/etc/logrotate.d/mayan) also needs adjustment so that it rotates the real log files.

**Comment by OnGle** [comment]
This *might* fix the bug. In-app it certainly seems that the setting reflect the fix. But I was not able to prove this, as I couldn't get any log output, at any point nor could I find any rdoc specifying how to handle this, or how to force a log entry. https://github.com/turnkeylinux-apps/mayan-edms/pull/2

**Comment by OnGle** [comment]
This needs more information to ensure this patch HAS fixed the issue.

**Comment by JedMeister** [comment]
I've merged the PR (https://github.com/turnkeylinux-apps/mayan-edms/pull/2) and am going to close this issue. If there are still issues, we'll deal with them if/when they crop up...

**Comment by DocCyblade** [comment]
I think this is still an issue. While looking into another issue, I found the logs were not being generated. More details to come as find them

**Comment by DocCyblade** [comment]
From a fresh install of v16.1, the config file is missing. Making a copy from the backup that is there and change the following and restarting the logs show up


copy /opt/mayan-edms/media/config_backup.yml to /opt/mayan-edms/media/config.yml

Then edit
/opt/mayan-edms/media/config.yml
`
LOGGING_ENABLE: true
LOGGING_HANDLERS:
- logfile
LOGGING_LEVEL: ERROR
LOGGING_LOG_FILE_PATH: /var/log/mayan/error.log
`
