### ISSUE TITLE
Replace di-live with default Debian installer and leverage default Debian Live support

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#2013]
Beyond the specific issue/feature noted in the subject, this is a meta-issue covering other install related bugs/issues.

Once the relevant Debian components (debian installer, debian live, etc) are integrated into TurnKey and this issue is closed, it should (or at least hopefully) also address the following issues:

- [x] #149
- [ ] #166
- [x] #1435
- [x] #1456
- [x] #1490

Preliminary work has already been done by @a3s7p - see https://github.com/a3s7p/tklive & internal testing is in progress. Once complete, "rc" builds of Core and Lamp will be published (perhaps others?). The anticipated ISO naming for v18.x based builds will include `uefi` in the name to differentiate from the current v18.x builds. E.g.
```
turnkey-core-uefi-18.0rc1-bookworm-amd64.iso
```
(or similar).

Assuming all goes well, these builds will be the default (probably only) builds for v19.x+

**Comment by OnGle** [comment]
Images built by tklive seem to not run correctly either in virtualized UEFI or BIOS with proxmox, it boots in both, so that's a promising start, but both fail to complete the install process (fail at "installing system")

(proxmox qemu/kvm environment is `QEMU emulator version 9.0.2 (pve-qemu-kvm_9.0.2-2)`)

I checked if the normal debian iso works on both just out of interest and had no issues. Not really sure what could be the issue here.

**Comment by JedMeister** [comment]
That sucks, but thanks for testing @OnGle. We'll need to relook at this although it's not priority (yet). I'll leave the PR unmerged and this issue open...

**Comment by a3s7p** [comment]
Thanks @OnGle, could you get detailed logs from the installer?

There's an option in the "main" menu to dump logs.

**Comment by JedMeister** [comment]
> Thanks [@OnGle](https://github.com/OnGle), could you get detailed logs from the installer?
> 
> There's an option in the "main" menu to dump logs.

Beyond that, I just had a quick poke around the debian docs and have some additional thoughts - apparently you should be able to access VT1 and/or VT4 and from there `dmesg` might have some info too? The manual also suggests checking in `/var/log` to see if there is anything there. The manual explictly notes `/var/log/syslog` although IIRC we don't install that anymore (just rely on the systemd journal). Perhaps I'm wrong, but I suspect that there isn't any journaling early in the install. If that's the case, then adding [`syslog-ng`](https://packages.debian.org/bookworm/syslog-ng) - or [`rsyslog`](https://packages.debian.org/bookworm/rsyslog) - to the ISO might be worth a try IMO.

There is also a [`installation-report`](https://packages.debian.org/bookworm/installation-report) package. AFAICT that's specifically intended to generate a report which can be attached to a new Debian bug. However pre-installing that give some additional info?

**Comment by OnGle** [comment]
Alright I've collected the logs + dmesg for both bios and uefi install attempts.
I had a quick look at `installation-report`, but it only includes hw info, which is already included in the debug logs.

This was tested from an up-to-date core-iso that has been hybridized using instructions from tklive. Let me know if you need any more info from my end.

[bios_install.tar.gz](https://github.com/user-attachments/files/18858710/bios_install.tar.gz)
[uefi_install.tar.gz](https://github.com/user-attachments/files/18858711/uefi_install.tar.gz)

**Comment by a3s7p** [comment]
Thanks @OnGle, looks like this is the culprit:

```
Feb 19 03:58:14 base-installer: error: The tar process copying the live system failed (only 39019 out of 39043 files have been copied, last file was ).
Feb 19 03:58:14 main-menu[828]: (process:6216): tar: ./var/spool/postfix/private/anvil: socket ignored
Feb 19 03:58:14 main-menu[828]: (process:6216): tar: ./var/spool/postfix/private/bounce: socket ignored
Feb 19 03:58:14 main-menu[828]: (process:6216): tar: ./var/spool/postfix/private/bsmtp: socket ignored
Feb 19 03:58:14 main-menu[828]: (process:6216): tar: ./var/spool/postfix/private/defer: socket ignored
Feb 19 03:58:14 main-menu[828]: (process:6216): tar: ./var/spool/postfix/private/discard: socket ignored
Feb 19 03:58:14 main-menu[828]: (process:6216): tar: ./var/spool/postfix/private/error: socket ignored
Feb 19 03:58:14 main-menu[828]: (process:6216): tar: ./var/spool/postfix/private/ifmail: socket ignored
Feb 19 03:58:14 main-menu[828]: (process:6216): tar: ./var/spool/postfix/private/lmtp: socket ignored
Feb 19 03:58:14 main-menu[828]: (process:6216): tar: ./var/spool/postfix/private/local: socket ignored
Feb 19 03:58:14 main-menu[828]: (process:6216): tar: ./var/spool/postfix/private/maildrop: socket ignored
Feb 19 03:58:14 main-menu[828]: (process:6216): tar: ./var/spool/postfix/private/mailman: socket ignored
Feb 19 03:58:14 main-menu[828]: (process:6216): tar: ./var/spool/postfix/private/proxymap: socket ignored
Feb 19 03:58:14 main-menu[828]: (process:6216): tar: ./var/spool/postfix/private/proxywrite: socket ignored
Feb 19 03:58:14 main-menu[828]: (process:6216): tar: ./var/spool/postfix/private/relay: socket ignored
Feb 19 03:58:14 main-menu[828]: (process:6216): tar: ./var/spool/postfix/private/retry: socket ignored
Feb 19 03:58:14 main-menu[828]: (process:6216): tar: ./var/spool/postfix/private/rewrite: socket ignored
Feb 19 03:58:14 main-menu[828]: (process:6216): tar: ./var/spool/postfix/private/scache: socket ignored
Feb 19 03:58:14 main-menu[828]: (process:6216): tar: ./var/spool/postfix/private/scalemail-backend: socket ignored
Feb 19 03:58:14 main-menu[828]: (process:6216): tar: ./var/spool/postfix/private/smtp: socket ignored
Feb 19 03:58:14 main-menu[828]: (process:6216): tar: ./var/spool/postfix/private/tlsmgr: socket ignored
Feb 19 03:58:14 main-menu[828]: (process:6216): tar: ./var/spool/postfix/private/trace: socket ignored
Feb 19 03:58:14 main-menu[828]: (process:6216): tar: ./var/spool/postfix/private/uucp: socket ignored
Feb 19 03:58:14 main-menu[828]: (process:6216): tar: ./var/spool/postfix/private/verify: socket ignored
Feb 19 03:58:14 main-menu[828]: (process:6216): tar: ./var/spool/postfix/private/virtual: socket ignored
Feb 19 03:58:14 main-menu[828]: (process:6216): tar: ./var/spool/postfix/public/cleanup: socket ignored
Feb 19 03:58:14 main-menu[828]: (process:6216): tar: ./var/spool/postfix/public/flush: socket ignored
Feb 19 03:58:14 main-menu[828]: (process:6216): tar: ./var/spool/postfix/public/pickup: socket ignored
Feb 19 03:58:14 main-menu[828]: (process:6216): tar: ./var/spool/postfix/public/postlog: socket ignored
Feb 19 03:58:14 main-menu[828]: (process:6216): tar: ./var/spool/postfix/public/qmgr: socket ignored
Feb 19 03:58:14 main-menu[828]: (process:6216): tar: ./var/spool/postfix/public/showq: socket ignored
Feb 19 03:58:14 main-menu[828]: WARNING **: Configuring 'live-installer' failed with error code 1
```

I ran into this a few times over the years. Maybe here as well but I don't remember what I did to fix it now. Basically `tar` returns 1 for this entirely non-serious error condition.

We'll need to avoid feeding it sockets. Maybe skip setting up / running postfix on the live system as the utility of that is questionable anyhow. I will handle that.

**Comment by a3s7p** [comment]
@OnGle @JedMeister fix is here, please check if it works for you

https://github.com/a3s7p/tklive/pull/1

**Comment by OnGle** [comment]
Still getting errors in the same place unfortunately. I'll post a new set of logs tomorrow.

**Comment by OnGle** [comment]
Here's the relevant logs, same as last time this includes install logs + dmesg, built from your tklive repo. Let me know if you need any more info.

[uefi_install.tar.gz](https://github.com/user-attachments/files/19382083/uefi_install.tar.gz)
[bios_install.tar.gz](https://github.com/user-attachments/files/19382082/bios_install.tar.gz)

**Comment by a3s7p** [comment]
@OnGle my bad, repo updated. Should be working now.

**Comment by OnGle** [comment]
That fixed bios install & UEFI live, but still having issues with uefi install (havn't checked bios live). Interesting the UEFI install doesn't error at all anymore, it just won't boot from the hdd after install. I'll get back to you tomorrow with whatever information I can scrape together from the boot screen.

**Comment by OnGle** [comment]
![Image](https://github.com/user-attachments/assets/e54a29e3-c8ee-43a8-9aee-307ff5448b0e)

This is about as much output as I get relating too it. I double checked and sure enough an EFI partition exists "sda1", it's only file is ``/EFI/debian/grubx64.efi`` although I'm not sure about that UUID, doesn't seem to match any device or partition uuid...

**Comment by a3s7p** [comment]
@OnGle thanks! That's weird. Is the environment sane? Does something like vanilla Debian boot ok in UEFI mode?

If yes, something in grub must have bitrotted – will look into it.

**Comment by OnGle** [comment]
@a3s7p My goodness, this was an issue on my end.

:|

Debian installed fine on proxmox. Out of interest after your last comment I tried installing the hybrid iso on a local virtlib VM. That worked fine. So I decided to go rooting around in the Proxmox UEFI config.

There is an option "Pre-enroll Keys". It adds many/all of the keys you normally would have pre-enrolled, like windows, debian, etc. It is enabled by default, and although it doesn't explicitly say so, it enables secure boot...

Obviously secure boot breaks the install. Disabling secure boot makes it work as expected.

**Comment by a3s7p** [comment]
@OnGle Thanks for digging into it! So do I understand it right that we can go ahead with using tklive for the test release and the rest of the plan?

There is an option to make secure boot work in `lb`. I didn't look into it for the test builds but it's certainly something we could do when this is at a more mature stage.

**Comment by OnGle** [comment]
Yep! We should be good to go, I couldn't find any other issues! 🥳

**Comment by OnGle** [comment]
Ok this is an interesting one. I was just testing odoo uefi build.

It seems like the livebuild stuff overrides the kernel commandline arguments, meaning it doesn't use legacy interface names. Which leads to the primary interface not being configured, and confconsole not being able to configure it.

**Comment by a3s7p** [comment]
@OnGle hmm, right. Sounds like a quick fix – will take a look.

**Comment by JedMeister** [comment]
Closing this and other di-live related issues as they are no longer relevant in v19.x. `di-live` has been superseded/replaced by [tkl-installer](https://github.com/turnkeylinux/tkl-installer).
